// packages/ui/src/components/AuthScreen.tsx
/**
 * First-run admin creation + login. No part of the app is reachable without
 * passing through here (CLAUDE.md §9). No masjid/prayer details are collected.
 */
import { useState, type FormEvent } from 'react';
import { motion } from 'motion/react';
import { useTranslation } from 'react-i18next';
import { trpc } from '../lib/trpc';
import { MasjidMark } from './Glyphs';
import { Modal } from './Modal';
import { fadeRise } from '../lib/motion';

export function AuthScreen({
  setupRequired,
  onAuthed,
}: {
  setupRequired: boolean;
  onAuthed: () => void;
}) {
  const { t } = useTranslation();
  const [username, setUsername] = useState('');
  const [password, setPassword] = useState('');
  const [confirm, setConfirm] = useState('');
  const [error, setError] = useState('');
  const [showReset, setShowReset] = useState(false);

  const setup = trpc.auth.setup.useMutation();
  const login = trpc.auth.login.useMutation();
  const busy = setup.isPending || login.isPending;

  async function submit(e: FormEvent) {
    e.preventDefault();
    setError('');
    try {
      if (setupRequired) {
        if (password.length < 8) return setError(t('auth.passwordTooShort'));
        if (password !== confirm) return setError(t('auth.passwordsMismatch'));
        await setup.mutateAsync({ username, password });
      } else {
        await login.mutateAsync({ username, password });
      }
      onAuthed();
    } catch (err) {
      setError((err as Error).message || t('auth.genericError'));
    }
  }

  return (
    <div className="auth-wrap">
      <motion.div className="auth-card glass-raised" variants={fadeRise} initial="initial" animate="animate">
        <div className="auth-logo">
          <MasjidMark size={48} />
        </div>
        <h1 className="page-title" style={{ textAlign: 'center', fontSize: '1.5rem' }}>
          {setupRequired ? t('auth.setupTitle') : t('auth.loginTitle')}
        </h1>
        <p className="page-sub" style={{ textAlign: 'center', marginBottom: '1.25rem' }}>
          {setupRequired ? t('auth.setupSubtitle') : t('auth.loginSubtitle')}
        </p>

        <form onSubmit={submit}>
          <div className="field">
            <label className="label" htmlFor="username">
              {t('auth.username')}
            </label>
            <input
              id="username"
              className="input glass-inset"
              autoComplete="username"
              placeholder={t('auth.usernamePlaceholder')}
              value={username}
              onChange={(e) => setUsername(e.target.value)}
              required
            />
          </div>

          <div className="field">
            <label className="label" htmlFor="password">
              {t('auth.password')}
            </label>
            <input
              id="password"
              type="password"
              className="input glass-inset"
              autoComplete={setupRequired ? 'new-password' : 'current-password'}
              value={password}
              onChange={(e) => setPassword(e.target.value)}
              required
            />
            {setupRequired && <span className="hint">{t('auth.passwordHint')}</span>}
          </div>

          {setupRequired && (
            <div className="field">
              <label className="label" htmlFor="confirm">
                {t('auth.confirmPassword')}
              </label>
              <input
                id="confirm"
                type="password"
                className="input glass-inset"
                autoComplete="new-password"
                value={confirm}
                onChange={(e) => setConfirm(e.target.value)}
                required
              />
            </div>
          )}

          {error && <p className="form-error">{error}</p>}

          <button type="submit" className="btn btn--primary btn--block" disabled={busy}>
            {busy ? t('auth.working') : setupRequired ? t('auth.createAccount') : t('auth.signIn')}
          </button>
        </form>

        {!setupRequired && (
          <button
            type="button"
            className="btn btn--ghost btn--block"
            style={{ marginTop: '0.6rem', border: 'none', color: 'var(--color-ink-muted)' }}
            onClick={() => setShowReset(true)}
          >
            {t('auth.forgotPassword')}
          </button>
        )}
      </motion.div>

      <Modal open={showReset} onClose={() => setShowReset(false)} title={t('auth.resetTitle')}>
        <p>{t('auth.resetIntro')}</p>
        <pre className="logs glass-inset" style={{ marginTop: '0.75rem' }}>
          {t('auth.resetCmd')}
        </pre>
        <p style={{ marginTop: '0.75rem' }}>{t('auth.resetOutro')}</p>
        <button className="btn btn--primary" style={{ marginTop: '1rem' }} onClick={() => setShowReset(false)}>
          {t('auth.resetClose')}
        </button>
      </Modal>
    </div>
  );
}

// frontend/src/lib/components/AuthScreen.svelte
<script lang="ts">
  import { t } from '$lib/i18n';
  import { api, ApiError } from '$lib/api/client';
  import { riseIn, pressable } from '$lib/animations';

  // mode: 'setup' for first-run admin creation, 'login' for returning admins.
  // onAuthed is called once a session has been established.
  let { mode, onAuthed }: { mode: 'setup' | 'login'; onAuthed: () => void } = $props();

  let username = $state('');
  let password = $state('');
  let confirm = $state('');
  let error = $state('');
  let busy = $state(false);
  let showReset = $state(false);

  async function submit() {
    error = '';
    if (mode === 'setup') {
      if (password.length < 8) { error = $t('auth.passwordTooShort'); return; }
      if (password !== confirm) { error = $t('auth.passwordsMismatch'); return; }
    }
    busy = true;
    try {
      if (mode === 'setup') {
        await api.auth.setup(username.trim(), password);
      } else {
        await api.auth.login(username.trim(), password);
      }
      onAuthed();
    } catch (e) {
      error = e instanceof ApiError ? e.message : $t('auth.genericError');
      busy = false;
    }
  }
</script>

<div class="auth-screen">
  <div class="auth-card glass-raised glow-accent" in:riseIn>
    <!-- Logo -->
    <div class="auth-logo" aria-hidden="true">
      <svg viewBox="0 0 40 40" width="48" height="48" fill="none" xmlns="http://www.w3.org/2000/svg" color="var(--color-primary)">
        <circle cx="20" cy="20" r="17" stroke="currentColor" stroke-width="1.8"/>
        <rect x="8" y="23" width="3" height="8.5" rx="0.8" fill="currentColor"/>
        <path d="M8 23 Q9.5 19.2 11 23 Z" fill="currentColor"/>
        <rect x="29" y="23" width="3" height="8.5" rx="0.8" fill="currentColor"/>
        <path d="M29 23 Q30.5 19.2 32 23 Z" fill="currentColor"/>
        <rect x="7" y="30.5" width="26" height="2" rx="0.8" fill="currentColor"/>
        <path d="M11 30.5 Q11 18 20 15 Q29 18 29 30.5 Z" fill="currentColor"/>
        <circle cx="20" cy="13" r="2.8" fill="currentColor"/>
        <circle cx="21.4" cy="11.8" r="2.1" fill="var(--color-surface-raised)"/>
      </svg>
    </div>

    <h1 class="auth-title">{mode === 'setup' ? $t('auth.setupTitle') : $t('auth.loginTitle')}</h1>
    <p class="auth-subtitle">{mode === 'setup' ? $t('auth.setupSubtitle') : $t('auth.loginSubtitle')}</p>

    <form class="auth-form" on:submit|preventDefault={submit}>
      <div class="auth-group">
        <label class="auth-label" for="auth-username">{$t('auth.username')}</label>
        <input
          id="auth-username"
          class="field"
          type="text"
          autocomplete="username"
          bind:value={username}
          placeholder={$t('auth.usernamePlaceholder')}
          required
        />
      </div>

      <div class="auth-group">
        <label class="auth-label" for="auth-password">{$t('auth.password')}</label>
        <input
          id="auth-password"
          class="field"
          type="password"
          autocomplete={mode === 'setup' ? 'new-password' : 'current-password'}
          aria-describedby={mode === 'setup' ? 'auth-password-hint' : undefined}
          bind:value={password}
          required
        />
        {#if mode === 'setup'}
          <span id="auth-password-hint" class="auth-hint">{$t('auth.passwordHint')}</span>
        {/if}
      </div>

      {#if mode === 'setup'}
        <div class="auth-group">
          <label class="auth-label" for="auth-confirm">{$t('auth.confirmPassword')}</label>
          <input
            id="auth-confirm"
            class="field"
            type="password"
            autocomplete="new-password"
            bind:value={confirm}
            required
          />
        </div>
      {/if}

      {#if error}
        <p class="auth-error" role="alert">{error}</p>
      {/if}

      <button type="submit" class="auth-submit" use:pressable disabled={busy}>
        {#if busy}
          {$t('auth.working')}
        {:else}
          {mode === 'setup' ? $t('auth.createAccount') : $t('auth.signIn')}
        {/if}
      </button>
    </form>

    {#if mode === 'login'}
      <button type="button" class="forgot-link" on:click={() => (showReset = true)}>
        {$t('auth.forgotPassword')}
      </button>
    {/if}
  </div>
</div>

<!-- Forgot-password instructions (reset is done from the server terminal). -->
{#if showReset}
  <svelte:window on:keydown={(e) => { if (e.key === 'Escape') showReset = false; }} />
  <div class="modal-scrim" on:click={() => (showReset = false)} role="presentation">
    <div
      class="reset-modal glass-raised"
      role="dialog"
      aria-modal="true"
      aria-labelledby="reset-title"
      on:click|stopPropagation
    >
      <h2 id="reset-title" class="reset-title">{$t('auth.resetTitle')}</h2>
      <p class="reset-text">{$t('auth.resetIntro')}</p>
      <pre class="reset-cmd"><code>{$t('auth.resetCmd')}</code></pre>
      <p class="reset-text">{$t('auth.resetOutro')}</p>
      <div class="reset-actions">
        <button class="auth-submit reset-close" use:pressable on:click={() => (showReset = false)}>
          {$t('auth.resetClose')}
        </button>
      </div>
    </div>
  </div>
{/if}

<style>
  .auth-screen {
    min-height: 100vh;
    display: flex;
    align-items: center;
    justify-content: center;
    padding: 1.5rem;
  }

  .auth-card {
    width: 100%;
    max-width: 24rem;
    padding: 2.25rem 2rem;
    display: flex;
    flex-direction: column;
    align-items: center;
    text-align: center;
  }

  .auth-logo {
    margin-block-end: 1rem;
  }

  .auth-title {
    font-family: 'Playfair Display', Georgia, serif;
    font-size: 1.5rem;
    font-weight: 600;
    color: var(--color-ink);
    margin: 0 0 0.375rem;
    letter-spacing: -0.02em;
  }

  .auth-subtitle {
    font-size: 0.9375rem;
    color: var(--color-ink-muted);
    margin: 0 0 1.75rem;
  }

  .auth-form {
    width: 100%;
    display: flex;
    flex-direction: column;
    gap: 1rem;
    text-align: start;
  }

  .auth-group {
    display: flex;
    flex-direction: column;
    gap: 0.375rem;
  }

  .auth-label {
    font-size: 0.8125rem;
    font-weight: 500;
    color: var(--color-ink-muted);
  }

  .field {
    width: 100%;
    box-sizing: border-box;
    padding: 0.5rem 0.75rem;
    border-radius: var(--radius-button);
    border: 1px solid var(--glass-border);
    background: var(--glass-bg-inset);
    color: var(--color-ink);
    font-size: 0.9375rem;
    transition: border-color 0.15s ease, box-shadow 0.15s ease;
    box-shadow: inset 0 1px 2px rgba(0, 0, 0, 0.18);
  }
  .field:focus {
    border-color: var(--color-primary);
    box-shadow: inset 0 1px 2px rgba(0, 0, 0, 0.18), var(--glow-primary);
  }
  .field::placeholder { color: var(--color-ink-faint); }

  .auth-hint {
    font-size: 0.75rem;
    color: var(--color-ink-faint);
  }

  .auth-error {
    margin: 0;
    font-size: 0.875rem;
    color: var(--color-danger);
    background: color-mix(in srgb, var(--color-danger) 12%, transparent);
    border: 1px solid color-mix(in srgb, var(--color-danger) 30%, transparent);
    padding: 0.5rem 0.75rem;
    border-radius: var(--radius-button);
  }

  .auth-submit {
    margin-block-start: 0.25rem;
    padding: 0.625rem 1.25rem;
    border-radius: var(--radius-button);
    background: var(--color-btn);
    color: var(--color-on-primary);
    font-size: 0.9375rem;
    font-weight: 600;
    border: none;
    cursor: pointer;
    box-shadow: var(--glow-primary);
    transition: background-color 0.15s ease;
  }
  .auth-submit:hover:not(:disabled) { background: var(--color-btn-hover); }
  .auth-submit:disabled { opacity: 0.6; cursor: not-allowed; }

  .forgot-link {
    margin-block-start: 1.25rem;
    background: none;
    border: none;
    color: var(--color-ink-muted);
    font-size: 0.8125rem;
    cursor: pointer;
    text-decoration: underline;
    text-underline-offset: 2px;
    transition: color 0.15s ease;
  }
  .forgot-link:hover { color: var(--color-primary); }

  /* Reset instructions modal */
  .modal-scrim {
    position: fixed;
    inset: 0;
    z-index: 50;
    display: flex;
    align-items: center;
    justify-content: center;
    padding: 1.5rem;
    background: rgba(0, 0, 0, 0.5);
    text-align: start;
  }
  .reset-modal {
    width: 100%;
    max-width: 30rem;
    padding: 1.75rem;
    box-shadow: var(--shadow-modal), var(--glass-shadow-raised);
  }
  .reset-title {
    font-size: 1.125rem;
    font-weight: 600;
    color: var(--color-ink);
    margin: 0 0 0.75rem;
  }
  .reset-text {
    font-size: 0.875rem;
    color: var(--color-ink-muted);
    line-height: 1.5;
    margin: 0 0 0.875rem;
  }
  .reset-cmd {
    margin: 0 0 0.875rem;
    padding: 0.75rem 0.875rem;
    border-radius: var(--radius-button);
    background: var(--glass-bg-inset);
    box-shadow: inset 0 1px 2px rgba(0, 0, 0, 0.25);
    overflow-x: auto;
  }
  .reset-cmd code {
    font-family: ui-monospace, SFMono-Regular, Menlo, monospace;
    font-size: 0.8125rem;
    color: var(--color-primary);
    white-space: pre;
  }
  .reset-actions {
    display: flex;
    justify-content: flex-end;
    margin-block-start: 0.25rem;
  }
  .reset-close { margin-block-start: 0; }

  @media (prefers-reduced-motion: reduce) {
    .field, .auth-submit, .forgot-link { transition: none; }
  }
</style>
